--------------------------------------------------------------------

# Trying logic:

In [32]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
import matplotlib.pyplot as plt

In [33]:


# Load the dataset
data = {
    'Temperature': [26.84, 30.19, 29.48, 31.76, 25.93, 27.45, 31.92, 31.71, 31.83, 29.37, 28.07, 26.27, 26.96, 28.39, 31.53],
    'Vibration_X': [-2.68, -23.72, 1.24, -13.17, -13.71, -2.78, -7.38, -0.67, -11.12, -11.81, -18.92, -22.18, -11.35, -0.69, 3.73],
    'Vibration_Y': [23.09, 23.3, 19.01, 21.69, 21.47, 27.26, 24.9, 5.46, 32.04, 19.66, 29.78, 14.3, 14.83, 17.6, 12.25],
    'Vibration_Z': [-1014.33, -1011.56, -1012.23, -1018.05, -1016.73, -1025.36, -1024.68, -1018.47, -1016.76, -1028.73, -1026.08, -1020.9, -1019.04, -1021.89, -1021.73]
}

df = pd.DataFrame(data)


In [45]:
df = pd.read_excel('/content/drive/MyDrive/V Sem7/End-Sem Project/Data/Material 1/finalyrdata_1.xlsx')
df_actual_values = pd.read_excel('/content/drive/MyDrive/V Sem7/End-Sem Project/Data/Material 1/finalyrdata_2.xlsx')

# actual_vibration_11th_day = df_actual_values[['Vibration_X', 'Vibration_Y', 'Vibration_Z']].values
# actual_vibration_11th_day = df_actual_values[['Vibration_X', 'Vibration_Y', 'Vibration_Z']].values

In [46]:
# Split the data into features (X) and target variables (y_vibration, y_temperature)
X = df[['Vibration_X', 'Vibration_Y', 'Vibration_Z']]
y_vibration = X  # Assuming vibration values are similar to the input features
y_temperature = df['Temperature']


In [ ]:
# Trial
# Create linear regression models
model_vibration = LinearRegression()
model_temperature = LinearRegression()

# Train the models
model_vibration.fit(X, y_vibration)
model_temperature.fit(X, y_temperature)


# Predict the 11th day values for all 1200 records
vibration_11th_day_prediction = model_vibration.predict(X)
temperature_11th_day_prediction = model_temperature.predict(X)

# Actual values for the 11th day
# actual_vibration_11th_day = np.array([[-2.51,5,-1021]])  # Replace with the actual values
actual_vibration_11th_day = df_actual_values[['Vibration_X', 'Vibration_Y', 'Vibration_Z']].values
actual_temperature_11th_day = df_actual_values['Temperature']  # Replace with the actual value

vibration_error = np.abs(vibration_11th_day_prediction[0] - actual_vibration_11th_day)
temperature_error = np.abs(temperature_11th_day_prediction[0] - actual_temperature_11th_day)

# Calculate mean errors
mean_vibration_error = vibration_error.mean(axis=0)
mean_temperature_error = temperature_error.mean()

# Display results
print("Linear Regression - Actual Vibration on the 11th day: \n", actual_vibration_11th_day)
print("Linear Regression - Predicted Vibration on the 11th day: \n", vibration_11th_day_prediction[0])
print("Linear Regression - Vibration Error for the 11th day: \n", vibration_error)
print("Linear Regression - Mean Vibration Error for the 11th day: \n", mean_vibration_error)

print("\nLinear Regression - Actual Temperature on the 11th day: \n", actual_temperature_11th_day)
print("Linear Regression - Predicted Temperature on the 11th day: \n", temperature_11th_day_prediction[0])
print("Linear Regression - Temperature Error for the 11th day: \n", temperature_error)
print("Linear Regression - Mean Temperature Error for the 11th day: \n", mean_temperature_error)

In [21]:
from sklearn.ensemble import RandomForestRegressor

# Create random forest models
model_vibration = RandomForestRegressor()
model_temperature = RandomForestRegressor()

In [64]:
model_vibration.fit(X, y_vibration)
model_temperature.fit(X, y_temperature)

# Predict the 11th day values
vibration_11th_day_prediction = model_vibration.predict(X.iloc[[-1]])
temperature_11th_day_prediction = model_temperature.predict(X.iloc[[-1]])

actual_vibration_11th_day = df_actual_values[['Vibration_X', 'Vibration_Y', 'Vibration_Z']].values
actual_temperature_11th_day = df_actual_values['Temperature']  # Replace with the actual value

vibration_error = np.abs(vibration_11th_day_prediction[0] - actual_vibration_11th_day)
temperature_error = np.abs(temperature_11th_day_prediction[0] - actual_temperature_11th_day)

# Calculate mean errors
mean_vibration_error = vibration_error.mean(axis=0)
mean_temperature_error = temperature_error.mean()

# Display results
print("RFG - Actual Vibration on the 11th day: \n", actual_vibration_11th_day)
print("RFG - Predicted Vibration on the 11th day: \n", vibration_11th_day_prediction[0])
print("RFG - Vibration Error for the 11th day: \n", vibration_error)
print("RFG - Mean Vibration Error for the 11th day: \n", mean_vibration_error)

print("\nRFG - Actual Temperature on the 11th day: \n", actual_temperature_11th_day)
print("RFG - Predicted Temperature on the 11th day: \n", temperature_11th_day_prediction[0])
print("RFG - Temperature Error for the 11th day: \n", temperature_error)
print("RFG - Mean Temperature Error for the 11th day: \n", mean_temperature_error)

RFG - Actual Vibration on the 11th day: 
 [[    1.69    12.06 -1028.63]
 [   -7.66    14.37 -1028.32]
 [   -1.13    10.25 -1028.11]
 ...
 [   -1.66     6.28 -1028.14]
 [   -1.98     9.66 -1022.77]
 [   -1.86    34.75 -1019.18]]
RFG - Predicted Vibration on the 11th day: 
 [  -23.31    26.69 -1028.95]
RFG - Vibration Error for the 11th day: 
 [[25.   14.63  0.32]
 [15.65 12.32  0.63]
 [22.18 16.44  0.84]
 ...
 [21.65 20.41  0.81]
 [21.33 17.03  6.18]
 [21.45  8.06  9.77]]
RFG - Mean Vibration Error for the 11th day: 
 [13.4493      8.94266667  8.382875  ]

RFG - Actual Temperature on the 11th day: 
 0       26.45
1       31.60
2       28.22
3       30.94
4       27.73
        ...  
1195    30.33
1196    26.44
1197    25.97
1198    25.68
1199    28.17
Name: Temperature, Length: 1200, dtype: float64
RFG - Predicted Temperature on the 11th day: 
 28.79235265169681
RFG - Temperature Error for the 11th day: 
 0       2.342353
1       2.807647
2       0.572353
3       2.147647
4       1.06235

In [23]:
from xgboost import XGBRegressor

# Create XGBoost models
model_vibration = XGBRegressor()
model_temperature = XGBRegressor()

# ... (rest of the code is similar to Linear Regression)


In [65]:
model_vibration.fit(X, y_vibration)
model_temperature.fit(X, y_temperature)

# Predict the 11th day values
vibration_11th_day_prediction = model_vibration.predict(X.iloc[[-1]])
temperature_11th_day_prediction = model_temperature.predict(X.iloc[[-1]])

# Actual values for the 11th day
actual_vibration_11th_day = df_actual_values[['Vibration_X', 'Vibration_Y', 'Vibration_Z']].values
actual_temperature_11th_day = df_actual_values['Temperature']  # Replace with the actual value

vibration_error = np.abs(vibration_11th_day_prediction[0] - actual_vibration_11th_day)
temperature_error = np.abs(temperature_11th_day_prediction[0] - actual_temperature_11th_day)

# Calculate mean errors
mean_vibration_error = vibration_error.mean(axis=0)
mean_temperature_error = temperature_error.mean()

# Display results
print("XGBoost - Actual Vibration on the 11th day: \n", actual_vibration_11th_day)
print("XGBoost - Predicted Vibration on the 11th day: \n", vibration_11th_day_prediction[0])
print("XGBoost - Vibration Error for the 11th day: \n", vibration_error)
print("XGBoost - Mean Vibration Error for the 11th day: \n", mean_vibration_error)

print("\nXGBoost - Actual Temperature on the 11th day: \n", actual_temperature_11th_day)
print("XGBoost - Predicted Temperature on the 11th day: \n", temperature_11th_day_prediction[0])
print("XGBoost - Temperature Error for the 11th day: \n", temperature_error)
print("XGBoost - Mean Temperature Error for the 11th day: \n", mean_temperature_error)

XGBoost - Actual Vibration on the 11th day: 
 [[    1.69    12.06 -1028.63]
 [   -7.66    14.37 -1028.32]
 [   -1.13    10.25 -1028.11]
 ...
 [   -1.66     6.28 -1028.14]
 [   -1.98     9.66 -1022.77]
 [   -1.86    34.75 -1019.18]]
XGBoost - Predicted Vibration on the 11th day: 
 [  -23.31    26.69 -1028.95]
XGBoost - Vibration Error for the 11th day: 
 [[25.   14.63  0.32]
 [15.65 12.32  0.63]
 [22.18 16.44  0.84]
 ...
 [21.65 20.41  0.81]
 [21.33 17.03  6.18]
 [21.45  8.06  9.77]]
XGBoost - Mean Vibration Error for the 11th day: 
 [13.4493      8.94266667  8.382875  ]

XGBoost - Actual Temperature on the 11th day: 
 0       26.45
1       31.60
2       28.22
3       30.94
4       27.73
        ...  
1195    30.33
1196    26.44
1197    25.97
1198    25.68
1199    28.17
Name: Temperature, Length: 1200, dtype: float64
XGBoost - Predicted Temperature on the 11th day: 
 28.79235265169681
XGBoost - Temperature Error for the 11th day: 
 0       2.342353
1       2.807647
2       0.572353
3   

In [ ]:
#LSTM models
from keras.models import Sequential
from keras.layers import LSTM, Dense

# Create LSTM models
model_vibration = Sequential()
model_temperature = Sequential()

# Add LSTM layers to the models
model_vibration.add(LSTM(units=50, activation='relu', input_shape=(X.shape[1], 1)))
model_vibration.add(Dense(units=X.shape[1]))  # Output layer for vibration

model_temperature.add(LSTM(units=50, activation='relu', input_shape=(X.shape[1], 1)))
model_temperature.add(Dense(units=1))  # Output layer for temperature

# Compile the models
model_vibration.compile(optimizer='adam', loss='mean_squared_error')
model_temperature.compile(optimizer='adam', loss='mean_squared_error')

# Reshape the input data for LSTM
X_lstm = np.array(X).reshape(X.shape[0], X.shape[1], 1)

# Train the models
model_vibration.fit(X_lstm, y_vibration, epochs=100, batch_size=32)
model_temperature.fit(X_lstm, y_temperature, epochs=100, batch_size=32)

# Predict the 11th day values
X_11th_day = np.array(X.iloc[[-1]]).reshape(1, X.shape[1], 1)
vibration_11th_day_prediction = model_vibration.predict(X_11th_day)
temperature_11th_day_prediction = model_temperature.predict(X_11th_day)


# Actual values for the 11th day
# actual_vibration_11th_day = np.array([[-2.51,5,-1021]])  # Replace with the actual values
actual_vibration_11th_day = df_actual_values[['Vibration_X', 'Vibration_Y', 'Vibration_Z']].values
actual_temperature_11th_day = df_actual_values['Temperature']  # Replace with the actual value

vibration_error = np.abs(vibration_11th_day_prediction[0] - actual_vibration_11th_day)
temperature_error = np.abs(temperature_11th_day_prediction[0] - actual_temperature_11th_day)

# Calculate mean errors
mean_vibration_error = vibration_error.mean(axis=0)
mean_temperature_error = temperature_error.mean()

# Display results
print("LSTM - Actual Vibration on the 11th day:\n", actual_vibration_11th_day)
print("LSTM - Predicted Vibration on the 11th day:\n", vibration_11th_day_prediction[0])
print("LSTM - Vibration Error for the 11th day:\n", vibration_error)
print("LSTM - Mean Vibration Error for the 11th day: \n", mean_vibration_error)

print("\nLSTM - Actual Temperature on the 11th day:\n", actual_temperature_11th_day)
print("LSTM - Predicted Temperature on the 11th day:\n", temperature_11th_day_prediction[0][0])
print("LSTM - Temperature Error for the 11th day:\n", temperature_error)
print("LSTM - Mean Temperature Error for the 11th day: \n", mean_temperature_error)

In [ ]:
# GRU

from keras.layers import GRU

# Create GRU models
model_vibration = Sequential()
model_temperature = Sequential()

# Add GRU layers to the models
model_vibration.add(GRU(units=50, activation='relu', input_shape=(X.shape[1], 1)))
model_vibration.add(Dense(units=X.shape[1]))  # Output layer for vibration

model_temperature.add(GRU(units=50, activation='relu', input_shape=(X.shape[1], 1)))
model_temperature.add(Dense(units=1))  # Output layer for temperature

# Compile the models
model_vibration.compile(optimizer='adam', loss='mean_squared_error')
model_temperature.compile(optimizer='adam', loss='mean_squared_error')

# Reshape the input data for GRU
X_gru = np.array(X).reshape(X.shape[0], X.shape[1], 1)

# Train the models
model_vibration.fit(X_gru, y_vibration, epochs=100, batch_size=32)
model_temperature.fit(X_gru, y_temperature, epochs=100, batch_size=32)

# Predict the 11th day values
X_11th_day_gru = np.array(X.iloc[[-1]]).reshape(1, X.shape[1], 1)
vibration_11th_day_prediction_gru = model_vibration.predict(X_11th_day_gru)
temperature_11th_day_prediction_gru = model_temperature.predict(X_11th_day_gru)

actual_vibration_11th_day = df_actual_values[['Vibration_X', 'Vibration_Y', 'Vibration_Z']].values
actual_temperature_11th_day = df_actual_values['Temperature']  # Replace with the actual value

# Calculate errors
vibration_error_gru = np.abs(vibration_11th_day_prediction_gru[0] - actual_vibration_11th_day)
temperature_error_gru = np.abs(temperature_11th_day_prediction_gru[0][0] - actual_temperature_11th_day)


# Calculate mean errors
mean_vibration_error = vibration_error_gru.mean(axis=0)
mean_temperature_error = temperature_error_gru.mean()

# Display results
print("GRU - Actual Vibration on the 11th day:", actual_vibration_11th_day)
print("GRU - Predicted Vibration on the 11th day:", vibration_11th_day_prediction_gru[0])
print("GRU - Vibration Error for the 11th day:", vibration_error_gru)
print("GRU - Mean Vibration Error for the 11th day: \n", mean_vibration_error)

print("\nGRU - Actual Temperature on the 11th day:", actual_temperature_11th_day)
print("GRU - Predicted Temperature on the 11th day:", temperature_11th_day_prediction_gru[0][0])
print("GRU - Temperature Error for the 11th day:", temperature_error_gru)
print("GRU - Mean Temperature Error for the 11th day: \n", mean_temperature_error)



In [ ]:
from keras.models import Sequential
from keras.layers import Bidirectional, LSTM, Dense

# Create BiLSTM models
model_vibration_bilstm = Sequential()
model_temperature_bilstm = Sequential()

# Add BiLSTM layers to the models
model_vibration_bilstm.add(Bidirectional(LSTM(units=50, activation='relu'), input_shape=(X.shape[1], 1)))
model_vibration_bilstm.add(Dense(units=X.shape[1]))  # Output layer for vibration

model_temperature_bilstm.add(Bidirectional(LSTM(units=50, activation='relu'), input_shape=(X.shape[1], 1)))
model_temperature_bilstm.add(Dense(units=1))  # Output layer for temperature

# Compile the models
model_vibration_bilstm.compile(optimizer='adam', loss='mean_squared_error')
model_temperature_bilstm.compile(optimizer='adam', loss='mean_squared_error')

# Reshape the input data for BiLSTM
X_bilstm = np.array(X).reshape(X.shape[0], X.shape[1], 1)

# Train the models
model_vibration_bilstm.fit(X_bilstm, y_vibration, epochs=100, batch_size=32)
model_temperature_bilstm.fit(X_bilstm, y_temperature, epochs=100, batch_size=32)

# Predict the 11th day values
X_11th_day_bilstm = np.array(X.iloc[[-1]]).reshape(1, X.shape[1], 1)
vibration_11th_day_prediction_bilstm = model_vibration_bilstm.predict(X_11th_day_bilstm)
temperature_11th_day_prediction_bilstm = model_temperature_bilstm.predict(X_11th_day_bilstm)

# Actual values for the 11th day
actual_vibration_11th_day = df_actual_values[['Vibration_X', 'Vibration_Y', 'Vibration_Z']].values
actual_temperature_11th_day = df_actual_values['Temperature']  # Replace with the actual value

# Calculate errors
vibration_error_bilstm = np.abs(vibration_11th_day_prediction_bilstm[0] - actual_vibration_11th_day_bilstm)
temperature_error_bilstm = np.abs(temperature_11th_day_prediction_bilstm[0][0] - actual_temperature_11th_day_bilstm)


# Calculate mean errors
mean_vibration_error = vibration_error_bilstm.mean(axis=0)
mean_temperature_error = temperature_error_bilstm.mean()

# Display results
print("BiLSTM - Actual Vibration on the 11th day:", actual_vibration_11th_day_bilstm)
print("BiLSTM - Predicted Vibration on the 11th day:", vibration_11th_day_prediction_bilstm[0])
print("BiLSTM - Vibration Error for the 11th day:", vibration_error_bilstm)
print("BiLSTM - Mean Vibration Error for the 11th day: \n", mean_vibration_error)

print("\nBiLSTM - Actual Temperature on the 11th day:", actual_temperature_11th_day_bilstm)
print("BiLSTM - Predicted Temperature on the 11th day:", temperature_11th_day_prediction_bilstm[0][0])
print("BiLSTM - Temperature Error for the 11th day:", temperature_error_bilstm)
print("BiLSTM - Mean Temperature Error for the 11th day: \n", mean_temperature_error)

In [ ]:
from keras.models import Sequential
from keras.layers import LSTM, Dense

# Create Stacked LSTM models
model_vibration = Sequential()
model_temperature = Sequential()

# Add Stacked LSTM layers to the models
model_vibration.add(LSTM(units=50, activation='relu', return_sequences=True, input_shape=(X.shape[1], 1)))
model_vibration.add(LSTM(units=50, activation='relu'))
model_vibration.add(Dense(units=X.shape[1]))  # Output layer for vibration

model_temperature.add(LSTM(units=50, activation='relu', return_sequences=True, input_shape=(X.shape[1], 1)))
model_temperature.add(LSTM(units=50, activation='relu'))
model_temperature.add(Dense(units=1))  # Output layer for temperature

# Compile the models
model_vibration.compile(optimizer='adam', loss='mean_squared_error')
model_temperature.compile(optimizer='adam', loss='mean_squared_error')

# Reshape the input data for Stacked LSTM
X_stacked_lstm = np.array(X).reshape(X.shape[0], X.shape[1], 1)

# Train the models
model_vibration.fit(X_stacked_lstm, y_vibration, epochs=100, batch_size=32)
model_temperature.fit(X_stacked_lstm, y_temperature, epochs=100, batch_size=32)

# Predict the 11th day values
X_11th_day_stacked_lstm = np.array(X.iloc[[-1]]).reshape(1, X.shape[1], 1)
vibration_11th_day_prediction_stacked_lstm = model_vibration.predict(X_11th_day_stacked_lstm)
temperature_11th_day_prediction_stacked_lstm = model_temperature.predict(X_11th_day_stacked_lstm)

# Actual values for the 11th day
actual_vibration_11th_day = df_actual_values[['Vibration_X', 'Vibration_Y', 'Vibration_Z']].values
actual_temperature_11th_day = df_actual_values['Temperature']  # Replace with the actual value

# Calculate errors
vibration_error_stacked_lstm = np.abs(vibration_11th_day_prediction_stacked_lstm[0] - actual_vibration_11th_day)
temperature_error_stacked_lstm = np.abs(temperature_11th_day_prediction_stacked_lstm[0][0] - actual_temperature_11th_day)

mean_vibration_error = vibration_error_stacked_lstm.mean(axis=0)
mean_temperature_error = temperature_error_stacked_lstm.mean()

# Display results
print("Stacked LSTM - Actual Vibration on the 11th day:", actual_vibration_11th_day)
print("Stacked LSTM - Predicted Vibration on the 11th day:", vibration_11th_day_prediction_stacked_lstm[0])
print("Stacked LSTM - Vibration Error for the 11th day:", vibration_error_stacked_lstm)
print("Stacked LSTM - Mean Vibration Error for the 11th day: \n", mean_vibration_error)

print("\nStacked LSTM - Actual Temperature on the 11th day:", actual_temperature_11th_day)
print("Stacked LSTM - Predicted Temperature on the 11th day:", temperature_11th_day_prediction_stacked_lstm[0][0])
print("Stacked LSTM - Temperature Error for the 11th day:", temperature_error_stacked_lstm)
print("Stacked LSTM - Mean Temperature Error for the 11th day: \n", mean_temperature_error)



In [ ]:
from keras.models import Sequential
from keras.layers import Reshape, Conv1D, LSTM, Dense

# Assume X is a 2D array with shape (samples, features)

# Reshape X to include a time step dimension
X_reshaped = np.array(X).reshape(X.shape[0], X.shape[1], 1)

# Create ConvLSTM models
model_vibration = Sequential()
model_temperature = Sequential()

# Add Convolutional layer followed by LSTM layers to the models
model_vibration.add(Conv1D(filters=64, kernel_size=3, activation='relu', input_shape=(X.shape[1], 1)))
model_vibration.add(LSTM(units=50, activation='relu'))
model_vibration.add(Dense(units=X.shape[1]))  # Output layer for vibration

model_temperature.add(Conv1D(filters=64, kernel_size=3, activation='relu', input_shape=(X.shape[1], 1)))
model_temperature.add(LSTM(units=50, activation='relu'))
model_temperature.add(Dense(units=1))  # Output layer for temperature

# Compile the models
model_vibration.compile(optimizer='adam', loss='mean_squared_error')
model_temperature.compile(optimizer='adam', loss='mean_squared_error')

# Train the models
model_vibration.fit(X_reshaped, y_vibration, epochs=100, batch_size=32)
model_temperature.fit(X_reshaped, y_temperature, epochs=100, batch_size=32)

# Predict the 11th day values
X_11th_day_reshaped = np.array(X.iloc[[-1]]).reshape(1, X.shape[1], 1)
vibration_11th_day_prediction = model_vibration.predict(X_11th_day_reshaped)
temperature_11th_day_prediction = model_temperature.predict(X_11th_day_reshaped)

# Actual values for the 11th day
actual_vibration_11th_day = df_actual_values[['Vibration_X', 'Vibration_Y', 'Vibration_Z']].values
actual_temperature_11th_day = df_actual_values['Temperature']  # Replace with the actual value

# Calculate errors
vibration_error = np.abs(vibration_11th_day_prediction[0] - actual_vibration_11th_day)
temperature_error = np.abs(temperature_11th_day_prediction[0][0] - actual_temperature_11th_day)


mean_vibration_error = vibration_error.mean(axis=0)
mean_temperature_error = temperature_error.mean()

# Display results
print("ConvLSTM - Actual Vibration on the 11th day:", actual_vibration_11th_day)
print("ConvLSTM - Predicted Vibration on the 11th day:", vibration_11th_day_prediction[0])
print("ConvLSTM - Vibration Error for the 11th day:", vibration_error)
print("ConvLSTM - Mean Vibration Error for the 11th day: \n", mean_vibration_error)


print("\nConvLSTM - Actual Temperature on the 11th day:", actual_temperature_11th_day)
print("ConvLSTM - Predicted Temperature on the 11th day:", temperature_11th_day_prediction[0][0])
print("ConvLSTM - Temperature Error for the 11th day:", temperature_error)
print("ConvLSTM - Mean Temperature Error for the 11th day: \n", mean_temperature_error)




# Actual values for the 11th day
