--------------------------------------------------------------------

# Trying logic:

In [5]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [6]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
import matplotlib.pyplot as plt

In [7]:
df = pd.read_excel('/content/drive/MyDrive/V Sem7/End-Sem Project/Data/Material 1/finalyrdata_1.xlsx')
df_actual_values = pd.read_excel('/content/drive/MyDrive/V Sem7/End-Sem Project/Data/Material 1/finalyrdata_2.xlsx')

# actual_vibration_11th_day = df_actual_values[['Vibration_X', 'Vibration_Y', 'Vibration_Z']].values
# actual_vibration_11th_day = df_actual_values[['Vibration_X', 'Vibration_Y', 'Vibration_Z']].values

In [8]:
# Split the data into features (X) and target variables (y_vibration, y_temperature)
X = df[['Vibration_X', 'Vibration_Y', 'Vibration_Z']]
y_vibration = X  # Assuming vibration values are similar to the input features
y_temperature = df['Temperature']


In [9]:
# Trial
# Create linear regression models
model_vibration = LinearRegression()
model_temperature = LinearRegression()

# Train the models
model_vibration.fit(X, y_vibration)
model_temperature.fit(X, y_temperature)


# Predict the 11th day values for all 1200 records
vibration_11th_day_prediction = model_vibration.predict(X)
temperature_11th_day_prediction = model_temperature.predict(X)

# Actual values for the 11th day
# actual_vibration_11th_day = np.array([[-2.51,5,-1021]])  # Replace with the actual values
actual_vibration_11th_day = df_actual_values[['Vibration_X', 'Vibration_Y', 'Vibration_Z']].values
actual_temperature_11th_day = df_actual_values['Temperature']  # Replace with the actual value

vibration_error = np.abs(vibration_11th_day_prediction[0] - actual_vibration_11th_day)
temperature_error = np.abs(temperature_11th_day_prediction[0] - actual_temperature_11th_day)

# Calculate mean errors
mean_vibration_error = vibration_error.mean(axis=0)
mean_temperature_error = temperature_error.mean()

# Display results
print("Linear Regression - Actual Vibration on the 11th day: \n", actual_vibration_11th_day)
print("Linear Regression - Predicted Vibration on the 11th day: \n", vibration_11th_day_prediction[0])
print("Linear Regression - Vibration Error for the 11th day: \n", vibration_error)
print("Linear Regression - Mean Vibration Error for the 11th day: \n", mean_vibration_error)

print("\nLinear Regression - Actual Temperature on the 11th day: \n", actual_temperature_11th_day)
print("Linear Regression - Predicted Temperature on the 11th day: \n", temperature_11th_day_prediction[0])
print("Linear Regression - Temperature Error for the 11th day: \n", temperature_error)
print("Linear Regression - Mean Temperature Error for the 11th day: \n", mean_temperature_error)

Linear Regression - Actual Vibration on the 11th day: 
 [[    1.69    12.06 -1028.63]
 [   -7.66    14.37 -1028.32]
 [   -1.13    10.25 -1028.11]
 ...
 [   -1.66     6.28 -1028.14]
 [   -1.98     9.66 -1022.77]
 [   -1.86    34.75 -1019.18]]
Linear Regression - Predicted Vibration on the 11th day: 
 [   -2.68    23.09 -1014.33]
Linear Regression - Vibration Error for the 11th day: 
 [[ 4.37 11.03 14.3 ]
 [ 4.98  8.72 13.99]
 [ 1.55 12.84 13.78]
 ...
 [ 1.02 16.81 13.81]
 [ 0.7  13.43  8.44]
 [ 0.82 11.66  4.85]]
Linear Regression - Mean Vibration Error for the 11th day: 
 [9.24011667 7.68758333 6.85400833]

Linear Regression - Actual Temperature on the 11th day: 
 0       26.45
1       31.60
2       28.22
3       30.94
4       27.73
        ...  
1195    30.33
1196    26.44
1197    25.97
1198    25.68
1199    28.17
Name: Temperature, Length: 1200, dtype: float64
Linear Regression - Predicted Temperature on the 11th day: 
 29.10503617452745
Linear Regression - Temperature Error for the 

In [10]:
from sklearn.ensemble import RandomForestRegressor

# Create random forest models
model_vibration = RandomForestRegressor()
model_temperature = RandomForestRegressor()

In [11]:
model_vibration.fit(X, y_vibration)
model_temperature.fit(X, y_temperature)

# Predict the 11th day values
vibration_11th_day_prediction = model_vibration.predict(X.iloc[[-1]])
temperature_11th_day_prediction = model_temperature.predict(X.iloc[[-1]])

actual_vibration_11th_day = df_actual_values[['Vibration_X', 'Vibration_Y', 'Vibration_Z']].values
actual_temperature_11th_day = df_actual_values['Temperature']  # Replace with the actual value

vibration_error = np.abs(vibration_11th_day_prediction[0] - actual_vibration_11th_day)
temperature_error = np.abs(temperature_11th_day_prediction[0] - actual_temperature_11th_day)

# Calculate mean errors
mean_vibration_error = vibration_error.mean(axis=0)
mean_temperature_error = temperature_error.mean()

# Display results
print("RFG - Actual Vibration on the 11th day: \n", actual_vibration_11th_day)
print("RFG - Predicted Vibration on the 11th day: \n", vibration_11th_day_prediction[0])
print("RFG - Vibration Error for the 11th day: \n", vibration_error)
print("RFG - Mean Vibration Error for the 11th day: \n", mean_vibration_error)

print("\nRFG - Actual Temperature on the 11th day: \n", actual_temperature_11th_day)
print("RFG - Predicted Temperature on the 11th day: \n", temperature_11th_day_prediction[0])
print("RFG - Temperature Error for the 11th day: \n", temperature_error)
print("RFG - Mean Temperature Error for the 11th day: \n", mean_temperature_error)

RFG - Actual Vibration on the 11th day: 
 [[    1.69    12.06 -1028.63]
 [   -7.66    14.37 -1028.32]
 [   -1.13    10.25 -1028.11]
 ...
 [   -1.66     6.28 -1028.14]
 [   -1.98     9.66 -1022.77]
 [   -1.86    34.75 -1019.18]]
RFG - Predicted Vibration on the 11th day: 
 [  -23.2189    26.5809 -1028.2292]
RFG - Vibration Error for the 11th day: 
 [[24.9089 14.5209  0.4008]
 [15.5589 12.2109  0.0908]
 [22.0889 16.3309  0.1192]
 ...
 [21.5589 20.3009  0.0892]
 [21.2389 16.9209  5.4592]
 [21.3589  8.1691  9.0492]]
RFG - Mean Vibration Error for the 11th day: 
 [13.3686135   8.8921155   7.78050433]

RFG - Actual Temperature on the 11th day: 
 0       26.45
1       31.60
2       28.22
3       30.94
4       27.73
        ...  
1195    30.33
1196    26.44
1197    25.97
1198    25.68
1199    28.17
Name: Temperature, Length: 1200, dtype: float64
RFG - Predicted Temperature on the 11th day: 
 27.265000000000022
RFG - Temperature Error for the 11th day: 
 0       0.815
1       4.335
2       0.95

In [12]:
from xgboost import XGBRegressor

# Create XGBoost models
model_vibration = XGBRegressor()
model_temperature = XGBRegressor()

# ... (rest of the code is similar to Linear Regression)


In [13]:
model_vibration.fit(X, y_vibration)
model_temperature.fit(X, y_temperature)

# Predict the 11th day values
vibration_11th_day_prediction = model_vibration.predict(X.iloc[[-1]])
temperature_11th_day_prediction = model_temperature.predict(X.iloc[[-1]])

# Actual values for the 11th day
actual_vibration_11th_day = df_actual_values[['Vibration_X', 'Vibration_Y', 'Vibration_Z']].values
actual_temperature_11th_day = df_actual_values['Temperature']  # Replace with the actual value

vibration_error = np.abs(vibration_11th_day_prediction[0] - actual_vibration_11th_day)
temperature_error = np.abs(temperature_11th_day_prediction[0] - actual_temperature_11th_day)

# Calculate mean errors
mean_vibration_error = vibration_error.mean(axis=0)
mean_temperature_error = temperature_error.mean()

# Display results
print("XGBoost - Actual Vibration on the 11th day: \n", actual_vibration_11th_day)
print("XGBoost - Predicted Vibration on the 11th day: \n", vibration_11th_day_prediction[0])
print("XGBoost - Vibration Error for the 11th day: \n", vibration_error)
print("XGBoost - Mean Vibration Error for the 11th day: \n", mean_vibration_error)

print("\nXGBoost - Actual Temperature on the 11th day: \n", actual_temperature_11th_day)
print("XGBoost - Predicted Temperature on the 11th day: \n", temperature_11th_day_prediction[0])
print("XGBoost - Temperature Error for the 11th day: \n", temperature_error)
print("XGBoost - Mean Temperature Error for the 11th day: \n", mean_temperature_error)

XGBoost - Actual Vibration on the 11th day: 
 [[    1.69    12.06 -1028.63]
 [   -7.66    14.37 -1028.32]
 [   -1.13    10.25 -1028.11]
 ...
 [   -1.66     6.28 -1028.14]
 [   -1.98     9.66 -1022.77]
 [   -1.86    34.75 -1019.18]]
XGBoost - Predicted Vibration on the 11th day: 
 [  -23.348892    26.688473 -1028.9445  ]
XGBoost - Vibration Error for the 11th day: 
 [[25.03889221 14.62847275  0.31445801]
 [15.68889221 12.31847275  0.62445801]
 [22.21889221 16.43847275  0.83445801]
 ...
 [21.68889221 20.40847275  0.80445801]
 [21.36889221 17.02847275  6.17445801]
 [21.48889221  8.06152725  9.76445801]]
XGBoost - Mean Vibration Error for the 11th day: 
 [13.48397704  8.94195395  8.37799805]

XGBoost - Actual Temperature on the 11th day: 
 0       26.45
1       31.60
2       28.22
3       30.94
4       27.73
        ...  
1195    30.33
1196    26.44
1197    25.97
1198    25.68
1199    28.17
Name: Temperature, Length: 1200, dtype: float64
XGBoost - Predicted Temperature on the 11th day: 
 2

In [14]:
#LSTM models
from keras.models import Sequential
from keras.layers import LSTM, Dense

# Create LSTM models
model_vibration = Sequential()
model_temperature = Sequential()

# Add LSTM layers to the models
model_vibration.add(LSTM(units=50, activation='relu', input_shape=(X.shape[1], 1)))
model_vibration.add(Dense(units=X.shape[1]))  # Output layer for vibration

model_temperature.add(LSTM(units=50, activation='relu', input_shape=(X.shape[1], 1)))
model_temperature.add(Dense(units=1))  # Output layer for temperature

# Compile the models
model_vibration.compile(optimizer='adam', loss='mean_squared_error')
model_temperature.compile(optimizer='adam', loss='mean_squared_error')

# Reshape the input data for LSTM
X_lstm = np.array(X).reshape(X.shape[0], X.shape[1], 1)

# Train the models
model_vibration.fit(X_lstm, y_vibration, epochs=100, batch_size=32)
model_temperature.fit(X_lstm, y_temperature, epochs=100, batch_size=32)

# Predict the 11th day values
X_11th_day = np.array(X.iloc[[-1]]).reshape(1, X.shape[1], 1)
vibration_11th_day_prediction = model_vibration.predict(X_11th_day)
temperature_11th_day_prediction = model_temperature.predict(X_11th_day)


# Actual values for the 11th day
# actual_vibration_11th_day = np.array([[-2.51,5,-1021]])  # Replace with the actual values
actual_vibration_11th_day = df_actual_values[['Vibration_X', 'Vibration_Y', 'Vibration_Z']].values
actual_temperature_11th_day = df_actual_values['Temperature']  # Replace with the actual value

vibration_error = np.abs(vibration_11th_day_prediction[0] - actual_vibration_11th_day)
temperature_error = np.abs(temperature_11th_day_prediction[0] - actual_temperature_11th_day)

# Calculate mean errors
mean_vibration_error = vibration_error.mean(axis=0)
mean_temperature_error = temperature_error.mean()

# Display results
print("LSTM - Actual Vibration on the 11th day:\n", actual_vibration_11th_day)
print("LSTM - Predicted Vibration on the 11th day:\n", vibration_11th_day_prediction[0])
print("LSTM - Vibration Error for the 11th day:\n", vibration_error)
print("LSTM - Mean Vibration Error for the 11th day: \n", mean_vibration_error)

print("\nLSTM - Actual Temperature on the 11th day:\n", actual_temperature_11th_day)
print("LSTM - Predicted Temperature on the 11th day:\n", temperature_11th_day_prediction[0][0])
print("LSTM - Temperature Error for the 11th day:\n", temperature_error)
print("LSTM - Mean Temperature Error for the 11th day: \n", mean_temperature_error)

Epoch 1/100
38/38 [==============================] - 1s 2ms/step - loss: 250188.9531
Epoch 2/100
38/38 [==============================] - 0s 2ms/step - loss: 162056.2500
Epoch 3/100
38/38 [==============================] - 0s 2ms/step - loss: 43133.1719
Epoch 4/100
38/38 [==============================] - 0s 2ms/step - loss: 1441.1653
Epoch 5/100
38/38 [==============================] - 0s 2ms/step - loss: 563.1345
Epoch 6/100
38/38 [==============================] - 0s 2ms/step - loss: 314.3326
Epoch 7/100
38/38 [==============================] - 0s 2ms/step - loss: 175.6313
Epoch 8/100
38/38 [==============================] - 0s 2ms/step - loss: 100.9395
Epoch 9/100
38/38 [==============================] - 0s 2ms/step - loss: 70.8356
Epoch 10/100
38/38 [==============================] - 0s 2ms/step - loss: 57.4343
Epoch 11/100
38/38 [==============================] - 0s 2ms/step - loss: 49.6807
Epoch 12/100
38/38 [==============================] - 0s 2ms/step - loss: 42.0479
Epoch 13

In [15]:
# GRU

from keras.layers import GRU

# Create GRU models
model_vibration = Sequential()
model_temperature = Sequential()

# Add GRU layers to the models
model_vibration.add(GRU(units=50, activation='relu', input_shape=(X.shape[1], 1)))
model_vibration.add(Dense(units=X.shape[1]))  # Output layer for vibration

model_temperature.add(GRU(units=50, activation='relu', input_shape=(X.shape[1], 1)))
model_temperature.add(Dense(units=1))  # Output layer for temperature

# Compile the models
model_vibration.compile(optimizer='adam', loss='mean_squared_error')
model_temperature.compile(optimizer='adam', loss='mean_squared_error')

# Reshape the input data for GRU
X_gru = np.array(X).reshape(X.shape[0], X.shape[1], 1)

# Train the models
model_vibration.fit(X_gru, y_vibration, epochs=100, batch_size=32)
model_temperature.fit(X_gru, y_temperature, epochs=100, batch_size=32)

# Predict the 11th day values
X_11th_day_gru = np.array(X.iloc[[-1]]).reshape(1, X.shape[1], 1)
vibration_11th_day_prediction_gru = model_vibration.predict(X_11th_day_gru)
temperature_11th_day_prediction_gru = model_temperature.predict(X_11th_day_gru)

actual_vibration_11th_day = df_actual_values[['Vibration_X', 'Vibration_Y', 'Vibration_Z']].values
actual_temperature_11th_day = df_actual_values['Temperature']  # Replace with the actual value

# Calculate errors
vibration_error_gru = np.abs(vibration_11th_day_prediction_gru[0] - actual_vibration_11th_day)
temperature_error_gru = np.abs(temperature_11th_day_prediction_gru[0][0] - actual_temperature_11th_day)


# Calculate mean errors
mean_vibration_error = vibration_error_gru.mean(axis=0)
mean_temperature_error = temperature_error_gru.mean()

# Display results
print("GRU - Actual Vibration on the 11th day:", actual_vibration_11th_day)
print("GRU - Predicted Vibration on the 11th day:", vibration_11th_day_prediction_gru[0])
print("GRU - Vibration Error for the 11th day:", vibration_error_gru)
print("GRU - Mean Vibration Error for the 11th day: \n", mean_vibration_error)

print("\nGRU - Actual Temperature on the 11th day:", actual_temperature_11th_day)
print("GRU - Predicted Temperature on the 11th day:", temperature_11th_day_prediction_gru[0][0])
print("GRU - Temperature Error for the 11th day:", temperature_error_gru)
print("GRU - Mean Temperature Error for the 11th day: \n", mean_temperature_error)



Epoch 1/100
38/38 [==============================] - 1s 2ms/step - loss: 280718.5938
Epoch 2/100
38/38 [==============================] - 0s 2ms/step - loss: 164961.2031
Epoch 3/100
38/38 [==============================] - 0s 2ms/step - loss: 59116.2852
Epoch 4/100
38/38 [==============================] - 0s 2ms/step - loss: 1213.1193
Epoch 5/100
38/38 [==============================] - 0s 2ms/step - loss: 225.2176
Epoch 6/100
38/38 [==============================] - 0s 2ms/step - loss: 136.0142
Epoch 7/100
38/38 [==============================] - 0s 2ms/step - loss: 78.9848
Epoch 8/100
38/38 [==============================] - 0s 2ms/step - loss: 50.4790
Epoch 9/100
38/38 [==============================] - 0s 2ms/step - loss: 37.6944
Epoch 10/100
38/38 [==============================] - 0s 2ms/step - loss: 31.4481
Epoch 11/100
38/38 [==============================] - 0s 2ms/step - loss: 26.7871
Epoch 12/100
38/38 [==============================] - 0s 2ms/step - loss: 24.1976
Epoch 13/1

In [17]:
from keras.models import Sequential
from keras.layers import Bidirectional, LSTM, Dense

# Create BiLSTM models
model_vibration_bilstm = Sequential()
model_temperature_bilstm = Sequential()

# Add BiLSTM layers to the models
model_vibration_bilstm.add(Bidirectional(LSTM(units=50, activation='relu'), input_shape=(X.shape[1], 1)))
model_vibration_bilstm.add(Dense(units=X.shape[1]))  # Output layer for vibration

model_temperature_bilstm.add(Bidirectional(LSTM(units=50, activation='relu'), input_shape=(X.shape[1], 1)))
model_temperature_bilstm.add(Dense(units=1))  # Output layer for temperature

# Compile the models
model_vibration_bilstm.compile(optimizer='adam', loss='mean_squared_error')
model_temperature_bilstm.compile(optimizer='adam', loss='mean_squared_error')

# Reshape the input data for BiLSTM
X_bilstm = np.array(X).reshape(X.shape[0], X.shape[1], 1)

# Train the models
model_vibration_bilstm.fit(X_bilstm, y_vibration, epochs=100, batch_size=32)
model_temperature_bilstm.fit(X_bilstm, y_temperature, epochs=100, batch_size=32)

# Predict the 11th day values
X_11th_day_bilstm = np.array(X.iloc[[-1]]).reshape(1, X.shape[1], 1)
vibration_11th_day_prediction_bilstm = model_vibration_bilstm.predict(X_11th_day_bilstm)
temperature_11th_day_prediction_bilstm = model_temperature_bilstm.predict(X_11th_day_bilstm)

# Actual values for the 11th day
actual_vibration_11th_day = df_actual_values[['Vibration_X', 'Vibration_Y', 'Vibration_Z']].values
actual_temperature_11th_day = df_actual_values['Temperature']  # Replace with the actual value

# Calculate errors
vibration_error_bilstm = np.abs(vibration_11th_day_prediction_bilstm[0] - actual_vibration_11th_day)
temperature_error_bilstm = np.abs(temperature_11th_day_prediction_bilstm[0][0] - actual_temperature_11th_day)


# Calculate mean errors
mean_vibration_error = vibration_error_bilstm.mean(axis=0)
mean_temperature_error = temperature_error_bilstm.mean()

# Display results
print("BiLSTM - Actual Vibration on the 11th day:", actual_vibration_11th_day)
print("BiLSTM - Predicted Vibration on the 11th day:", vibration_11th_day_prediction_bilstm[0])
print("BiLSTM - Vibration Error for the 11th day:", vibration_error_bilstm)
print("BiLSTM - Mean Vibration Error for the 11th day: \n", mean_vibration_error)

print("\nBiLSTM - Actual Temperature on the 11th day:", actual_temperature_11th_day)
print("BiLSTM - Predicted Temperature on the 11th day:", temperature_11th_day_prediction_bilstm[0][0])
print("BiLSTM - Temperature Error for the 11th day:", temperature_error_bilstm)
print("BiLSTM - Mean Temperature Error for the 11th day: \n", mean_temperature_error)

Epoch 1/100
38/38 [==============================] - 2s 2ms/step - loss: 223300.9375
Epoch 2/100
38/38 [==============================] - 0s 2ms/step - loss: 42537.7227
Epoch 3/100
38/38 [==============================] - 0s 2ms/step - loss: 637.8463
Epoch 4/100
38/38 [==============================] - 0s 2ms/step - loss: 66.8313
Epoch 5/100
38/38 [==============================] - 0s 2ms/step - loss: 58.1483
Epoch 6/100
38/38 [==============================] - 0s 2ms/step - loss: 56.4015
Epoch 7/100
38/38 [==============================] - 0s 2ms/step - loss: 54.4590
Epoch 8/100
38/38 [==============================] - 0s 3ms/step - loss: 52.5936
Epoch 9/100
38/38 [==============================] - 0s 2ms/step - loss: 50.4755
Epoch 10/100
38/38 [==============================] - 0s 2ms/step - loss: 49.0744
Epoch 11/100
38/38 [==============================] - 0s 3ms/step - loss: 46.8658
Epoch 12/100
38/38 [==============================] - 0s 2ms/step - loss: 45.2967
Epoch 13/100
38/3

In [18]:
from keras.models import Sequential
from keras.layers import LSTM, Dense

# Create Stacked LSTM models
model_vibration = Sequential()
model_temperature = Sequential()

# Add Stacked LSTM layers to the models
model_vibration.add(LSTM(units=50, activation='relu', return_sequences=True, input_shape=(X.shape[1], 1)))
model_vibration.add(LSTM(units=50, activation='relu'))
model_vibration.add(Dense(units=X.shape[1]))  # Output layer for vibration

model_temperature.add(LSTM(units=50, activation='relu', return_sequences=True, input_shape=(X.shape[1], 1)))
model_temperature.add(LSTM(units=50, activation='relu'))
model_temperature.add(Dense(units=1))  # Output layer for temperature

# Compile the models
model_vibration.compile(optimizer='adam', loss='mean_squared_error')
model_temperature.compile(optimizer='adam', loss='mean_squared_error')

# Reshape the input data for Stacked LSTM
X_stacked_lstm = np.array(X).reshape(X.shape[0], X.shape[1], 1)

# Train the models
model_vibration.fit(X_stacked_lstm, y_vibration, epochs=100, batch_size=32)
model_temperature.fit(X_stacked_lstm, y_temperature, epochs=100, batch_size=32)

# Predict the 11th day values
X_11th_day_stacked_lstm = np.array(X.iloc[[-1]]).reshape(1, X.shape[1], 1)
vibration_11th_day_prediction_stacked_lstm = model_vibration.predict(X_11th_day_stacked_lstm)
temperature_11th_day_prediction_stacked_lstm = model_temperature.predict(X_11th_day_stacked_lstm)

# Actual values for the 11th day
actual_vibration_11th_day = df_actual_values[['Vibration_X', 'Vibration_Y', 'Vibration_Z']].values
actual_temperature_11th_day = df_actual_values['Temperature']  # Replace with the actual value

# Calculate errors
vibration_error_stacked_lstm = np.abs(vibration_11th_day_prediction_stacked_lstm[0] - actual_vibration_11th_day)
temperature_error_stacked_lstm = np.abs(temperature_11th_day_prediction_stacked_lstm[0][0] - actual_temperature_11th_day)

mean_vibration_error = vibration_error_stacked_lstm.mean(axis=0)
mean_temperature_error = temperature_error_stacked_lstm.mean()

# Display results
print("Stacked LSTM - Actual Vibration on the 11th day:", actual_vibration_11th_day)
print("Stacked LSTM - Predicted Vibration on the 11th day:", vibration_11th_day_prediction_stacked_lstm[0])
print("Stacked LSTM - Vibration Error for the 11th day:", vibration_error_stacked_lstm)
print("Stacked LSTM - Mean Vibration Error for the 11th day: \n", mean_vibration_error)

print("\nStacked LSTM - Actual Temperature on the 11th day:", actual_temperature_11th_day)
print("Stacked LSTM - Predicted Temperature on the 11th day:", temperature_11th_day_prediction_stacked_lstm[0][0])
print("Stacked LSTM - Temperature Error for the 11th day:", temperature_error_stacked_lstm)
print("Stacked LSTM - Mean Temperature Error for the 11th day: \n", mean_temperature_error)



Epoch 1/100
38/38 [==============================] - 2s 3ms/step - loss: 339654.1562
Epoch 2/100
38/38 [==============================] - 0s 3ms/step - loss: 218897.5000
Epoch 3/100
38/38 [==============================] - 0s 3ms/step - loss: 13767.7441
Epoch 4/100
38/38 [==============================] - 0s 3ms/step - loss: 3208.9700
Epoch 5/100
38/38 [==============================] - 0s 3ms/step - loss: 913.7526
Epoch 6/100
38/38 [==============================] - 0s 3ms/step - loss: 253.3135
Epoch 7/100
38/38 [==============================] - 0s 3ms/step - loss: 103.6959
Epoch 8/100
38/38 [==============================] - 0s 3ms/step - loss: 71.9318
Epoch 9/100
38/38 [==============================] - 0s 3ms/step - loss: 42.3399
Epoch 10/100
38/38 [==============================] - 0s 3ms/step - loss: 37.1541
Epoch 11/100
38/38 [==============================] - 0s 4ms/step - loss: 29.1083
Epoch 12/100
38/38 [==============================] - 0s 4ms/step - loss: 37.1277
Epoch 13/

In [19]:
from keras.models import Sequential
from keras.layers import Reshape, Conv1D, LSTM, Dense

# Assume X is a 2D array with shape (samples, features)

# Reshape X to include a time step dimension
X_reshaped = np.array(X).reshape(X.shape[0], X.shape[1], 1)

# Create ConvLSTM models
model_vibration = Sequential()
model_temperature = Sequential()

# Add Convolutional layer followed by LSTM layers to the models
model_vibration.add(Conv1D(filters=64, kernel_size=3, activation='relu', input_shape=(X.shape[1], 1)))
model_vibration.add(LSTM(units=50, activation='relu'))
model_vibration.add(Dense(units=X.shape[1]))  # Output layer for vibration

model_temperature.add(Conv1D(filters=64, kernel_size=3, activation='relu', input_shape=(X.shape[1], 1)))
model_temperature.add(LSTM(units=50, activation='relu'))
model_temperature.add(Dense(units=1))  # Output layer for temperature

# Compile the models
model_vibration.compile(optimizer='adam', loss='mean_squared_error')
model_temperature.compile(optimizer='adam', loss='mean_squared_error')

# Train the models
model_vibration.fit(X_reshaped, y_vibration, epochs=100, batch_size=32)
model_temperature.fit(X_reshaped, y_temperature, epochs=100, batch_size=32)

# Predict the 11th day values
X_11th_day_reshaped = np.array(X.iloc[[-1]]).reshape(1, X.shape[1], 1)
vibration_11th_day_prediction = model_vibration.predict(X_11th_day_reshaped)
temperature_11th_day_prediction = model_temperature.predict(X_11th_day_reshaped)

# Actual values for the 11th day
actual_vibration_11th_day = df_actual_values[['Vibration_X', 'Vibration_Y', 'Vibration_Z']].values
actual_temperature_11th_day = df_actual_values['Temperature']  # Replace with the actual value

# Calculate errors
vibration_error = np.abs(vibration_11th_day_prediction[0] - actual_vibration_11th_day)
temperature_error = np.abs(temperature_11th_day_prediction[0][0] - actual_temperature_11th_day)


mean_vibration_error = vibration_error.mean(axis=0)
mean_temperature_error = temperature_error.mean()

# Display results
print("ConvLSTM - Actual Vibration on the 11th day:", actual_vibration_11th_day)
print("ConvLSTM - Predicted Vibration on the 11th day:", vibration_11th_day_prediction[0])
print("ConvLSTM - Vibration Error for the 11th day:", vibration_error)
print("ConvLSTM - Mean Vibration Error for the 11th day: \n", mean_vibration_error)


print("\nConvLSTM - Actual Temperature on the 11th day:", actual_temperature_11th_day)
print("ConvLSTM - Predicted Temperature on the 11th day:", temperature_11th_day_prediction[0][0])
print("ConvLSTM - Temperature Error for the 11th day:", temperature_error)
print("ConvLSTM - Mean Temperature Error for the 11th day: \n", mean_temperature_error)




# Actual values for the 11th day


Epoch 1/100
38/38 [==============================] - 1s 2ms/step - loss: 253392.1562
Epoch 2/100
38/38 [==============================] - 0s 2ms/step - loss: 95272.2656
Epoch 3/100
38/38 [==============================] - 0s 2ms/step - loss: 11214.6504
Epoch 4/100
38/38 [==============================] - 0s 2ms/step - loss: 456.1640
Epoch 5/100
38/38 [==============================] - 0s 2ms/step - loss: 61.3530
Epoch 6/100
38/38 [==============================] - 0s 2ms/step - loss: 60.8623
Epoch 7/100
38/38 [==============================] - 0s 2ms/step - loss: 60.9853
Epoch 8/100
38/38 [==============================] - 0s 2ms/step - loss: 60.8558
Epoch 9/100
38/38 [==============================] - 0s 2ms/step - loss: 60.2923
Epoch 10/100
38/38 [==============================] - 0s 2ms/step - loss: 60.1881
Epoch 11/100
38/38 [==============================] - 0s 2ms/step - loss: 60.2527
Epoch 12/100
38/38 [==============================] - 0s 2ms/step - loss: 60.1737
Epoch 13/100
3